name: "sdsc-hackathon"
channels:
  - conda-forge
dependencies:
  - python==3.10.*
  - pyyaml
  - pandas
  - matplotlib
  - pip
  - git
  - pip: 
    - ipykernel
    - datetime
    - requests
    - pillow
    - gradio
    - retry-requests
    - requests-cache
    - openmeteo-requests
    - openai
    - python-dotenv
    