name: "sdsc-hackathon2"
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pyyaml
  - pandas
  - matplotlib
  - pip
  - gradio
  - git
  - pip: 
    - ipykernel
    - openai
    - request
    - requests
    - pillow
    - http
    - retry-requests
    - requests-cache
    - openmeteo-requests
    - datetime
    - dotenv
    - python-dotenv
    # - gradio==3.50.2
    - nixtlats
    - pydantic==1.10.13


